### ISSUE TITLE
Parse arguments (incl. shifted registers) from instruction stream

### ISSUE THREAD

**Issue by CameronDiver** [intolerable/GroupProject#3]

**Comment by CameronDiver** [comment]
This is nearly done @intolerable but we need to fix the rotated registers. The instruction I've found to not work is 
0x03007E40 
which is supposed to be 
mov r7, #3648 
according to the disassembler

but we are getting out (Rotated 28 64) for the value which I'm pretty sure isn't right

**Comment by intolerable** [comment]
fixed in dd81e6c, we don't have any way to access the absolute value yet though (there will be a lens for it tho)
